### ISSUE TITLE
Reading from SystemEvents

### ISSUE THREAD

**Issue by nmahadkar** [victor3dptz/postfix-log-to-mysql#1]
I am currently logging all activity from postfix to mysql using rsyslogd.  All events are being stored into the SystemEvents table.  How do I pharse them into MainView & NoQueue so that parser can render them?

**Comment by victor3dptz** [comment]
Import view.sql to the same database where SystemEvents table is. After import, there are 4 views, the most important is MainView. Doing SELECT * FROM MainView you'll get the data you need.
